Данил Копорушкин
urfu-2017/javascript-task-2 pull request #93
Opened 2017-10-11 16:54 UTC by darl0ck

2017-10-11 16:54 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 23

2017-10-11 17:09 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 23

2017-10-11 17:23 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 23

2017-10-11 19:06 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 23

2017-10-12 17:58 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 23

2017-10-12 18:05 UTC, honest-hrundel commented
:tomato: Пройдено тестов 19 из 23

2017-10-12 18:19 UTC, honest-hrundel commented
:tomato: Пройдено тестов 21 из 23

2017-10-12 18:45 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-12 19:12 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 23

2017-10-12 19:14 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 23

2017-10-12 19:18 UTC, honest-hrundel commented
:tomato: Пройдено тестов 21 из 23

2017-10-12 19:23 UTC, honest-hrundel commented
:tomato: Пройдено тестов 21 из 23

2017-10-12 19:43 UTC, honest-hrundel commented
:tomato: Пройдено тестов 24 из 26

2017-10-12 19:45 UTC, darl0ck commented
🔔 
ох эти 2 теста 
Прошу помочь найти ,что ж не так

2017-10-12 19:51 UTC, honest-hrundel commented
:tomato: Пройдено тестов 23 из 26

2017-10-12 19:53 UTC, honest-hrundel commented
:tomato: Пройдено тестов 24 из 26

2017-10-12 19:57 UTC, honest-hrundel commented
:tomato: Пройдено тестов 24 из 26

2017-10-12 20:05 UTC, honest-hrundel commented
:tomato: Пройдено тестов 21 из 26

2017-10-12 20:08 UTC, honest-hrundel commented
:tomato: Пройдено тестов 21 из 26

2017-10-12 20:17 UTC, honest-hrundel commented
:tomato: Пройдено тестов 24 из 26

2017-10-12 21:32 UTC, sameoldmadness commented on phone-book.js
> +/* eslint-disable max-len,valid-jsdoc,default-case,max-depth,no-unused-vars,linebreak-style,complexity,max-statements,no-undef,no-console */
Если что, я всё вижу.

2017-10-12 21:55 UTC, sameoldmadness requested changes

2017-10-12 21:55 UTC, sameoldmadness commented on phone-book.js
> +const regExpPhone = /^(\d{10}|\d{12})$/;
Судя по заданию, ровно десять цифр.

2017-10-12 21:55 UTC, sameoldmadness commented on phone-book.js
> +const regExpEmail = /^[-._a-z0-9]+@(?:[a-z0-9][-a-z0-9]+\.)+[a-z]{2,6}$/;
Зачем валидировать почту?

2017-10-12 21:55 UTC, sameoldmadness commented on phone-book.js
> +    return (((regExpPhone.test(phone) === true &&
`<expr> === true` эквивалентно `<expr>`.

2017-10-12 21:55 UTC, sameoldmadness commented on phone-book.js
> +        name !== undefined)) && !alreadyAdd(phone)) && !isNaN(Number(phone)) && isString(name) && isNaN(Number(name)) && isNaN(Number(email));
Тут как-то слишком много проверок.

Если name – строка, то оно не может быть undefined. Проверки на "не число" у name и email – зачем?

2017-10-12 21:55 UTC, sameoldmadness commented on phone-book.js
> +function isItGood2(phone, name, email) {
Чем отличается от первой?

2017-10-12 21:55 UTC, sameoldmadness commented on phone-book.js
> +            email: email === '' ? undefined : email
Судя по проверкам, пустой строки тут быть не может.

2017-10-12 21:55 UTC, sameoldmadness commented on phone-book.js
> +                inf.email = email === '' ? email.replace(undefined, '') : email;
Тут что-то непонятное мне происходит. `email.replace(undefined, '')` – это что?

2017-10-12 21:55 UTC, sameoldmadness commented on phone-book.js
> +    let lines = csv.split('\n');
Тут я бы ещё от пробелов по краям и пустых строк избавился.

2017-10-12 21:55 UTC, sameoldmadness commented on phone-book.js
> +        newIndexes = deleter(allIndexes, j);
Методы `findAndRemove` и `find` очень сложно написаны. Упростить можно так:

- использовать for-of вместо for
- искать по трём полям отдельно, не используя конкатенацию
- форматирование в строку вынести в функцию
- удаление реализовать по-другому

Навскидку, есть два варианта: идти по элементам обратном порядке и удалять ненужные с помощью splice. Либо скопировать в новый массив только нужные и заменить им старый.

2017-10-13 08:49 UTC, honest-hrundel commented
:tomato: Пройдено тестов 24 из 26

2017-10-18 17:59 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 26 из 26

2017-10-18 17:59 UTC, closed without merging